from django.conf import settings

PHOTOLOGUEEXT_MEDIA_PATH = getattr(settings, 'PHOTOLOGUEEXT_MEDIA_PATH', 'photologueext/')
PHOTOLOGUEEXT_MEDIA_URL = getattr(settings, 'PHOTOLOGUEEXT_MEDIA_URL', ''.join((settings.STATIC_URL, PHOTOLOGUEEXT_MEDIA_PATH)) )
PHOTOLOGUEEXT_DISABLE_WATERMARKS = getattr(settings, 'PHOTOLOGUEEXT_DISABLE_WATERMARKS', True)
PHOTOLOGUEEXT_GALLERYUPLOAD_NUM_IMAGEFIELDS = getattr(settings, 'PHOTOLOGUEEXT_GALLERYUPLOAD_NUM_IMAGEFIELDS', 5)
PHOTOLOGUEEXT_M2M_THUMBNAILS = getattr(settings, 'PHOTOLOGUEEXT_M2M_THUMBNAILS', False)
PHOTOLOGUEEXT_ONE_GALLERY_PER_PHOTO = getattr(settings, 'PHOTOLOGUEEXT_ONE_GALLERY_PER_PHOTO', False)
